version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: testimage:1.07
    container_name: testcontainer
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: myLogGroup
        awslogs-stream: test-logstream
        awslogs-create-group: "true"
    ports:
    - "3000:3000"
    volumes:
    - myvol:/test
    networks:
    - mynet
volumes:
  myvol:
networks:
  mynet:
    driver: bridge
